import { Inter } from 'next/font/google';

import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import StoreProvider from './StoreProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </StoreProvider>
      </body>
    </html>
  );
}
